[package]
name = "shallot-tor"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
arti-client = { version = "0.46", features = ["onion-service-client"] }
tor-rtcompat = "0.46"
tor-socksproto = "0.46"
futures = "0.3"

[profile.release]
strip = true
lto = "thin"
